### ISSUE TITLE
April fools trolling

### ISSUE THREAD

**Issue by zephsy** [zephsy/runebound#1]
## Todo

- [x] Sword Swing Animation
- [x] Combat System 
- [x] Make EXP and Level System
- [ ] Inventory System
- [ ] Mob System
- [ ] Simple Dialogue Option
- [ ] Shops
- [ ] Make a bunch of ugly areas
- [ ] Release
